services:
  grabogram:
    build: .
    container_name: grabogram
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
#     networks:
#       tinc_net:
#         ipv4_address:

# networks:
#   tinc_net:
#     external: true